import { Category } from '../types.ts';

export const componentLibrary: Record<Category, string[]> = {
  [Category.MICROCONTROLLER]: [
    'Arduino Uno',
    'Arduino Nano',
    'Arduino Mega',
    'Raspberry Pi 4',
    'Raspberry Pi Pico',
    'ESP32 Development Board',
    'ESP8266 NodeMCU',
  ],
  [Category.SENSOR]: [
    'Ultrasonic Sensor HC-SR04',
    'DHT11 Temperature & Humidity Sensor',
    'DHT22 Temperature & Humidity Sensor',
    'PIR Motion Sensor HC-SR501',
    'Soil Moisture Sensor',
    'LDR (Light Dependent Resistor)',
    'IR Proximity Sensor',
    'MPU-6050 Gyroscope/Accelerometer',
    'Flex Sensor',
    'Sound Sensor',
    'Rain Sensor',
  ],
  [Category.MOTOR]: [
    'SG90 Servo Motor',
    'MG996R Servo Motor',
    'DC Gear Motor (Yellow)',
    'NEMA 17 Stepper Motor',
    '28BYJ-48 Stepper Motor with ULN2003 Driver',
    'L298N Motor Driver',
    'L293D Motor Driver Shield',
    '5V DC Water Pump',
  ],
  [Category.DISPLAY]: [
    '16x2 I2C LCD Display',
    '0.96" OLED Display (I2C)',
    'MAX7219 8x8 Dot Matrix Display',
    '7-Segment Display (Single Digit)',
    '7-Segment Display (4-Digit)',
    'Nokia 5110 LCD',
  ],
  [Category.POWER_SUPPLY]: [
    '9V Battery',
    '9V Battery Snap Connector',
    'AA Battery Holder (4-cell)',
    'Breadboard Power Supply Module (MB102)',
    '5V 1A Power Adapter',
    '12V 2A Power Adapter',
    '18650 Lithium-ion Battery',
    'TP4056 Li-ion Charger Module',
  ],
  [Category.GENERAL]: [
    'Breadboard (830 point)',
    'Breadboard (400 point)',
    'Jumper Wires (Male-Male)',
    'Jumper Wires (Male-Female)',
    'Jumper Wires (Female-Female)',
    'Resistor Kit (Assorted)',
    'Capacitor Kit (Assorted)',
    'LEDs (Red)',
    'LEDs (Green)',
    'LEDs (Blue)',
    'RGB LED (Common Cathode/Anode)',
    'Push Buttons (Tactile)',
    'Potentiometer (10k Ohm)',
    'Active Buzzer',
    'Passive Buzzer',
    'USB Type-A to B Cable',
    'Micro USB Cable',
    'Soldering Iron',
    'Solder Wire',
  ],
};